### ISSUE TITLE
Develop Popup UI (Using Html and CSS)🎨

### ISSUE THREAD

**Issue by DestinedCodes** [ALX-Students-Contribution/ALX_Dark_Mode_Extension#7]
The Dark Mode Extension's user interface needs to be implemented, including a user-friendly interface for enabling or disabling the extension and any other user-facing components. This task involves working with HTML, CSS to create an intuitive and responsive interface that enhances the user experience. Join us in creating a visually appealing and user-friendly extension that will stand out from the rest.

**Comment by sebzz2k2** [comment]
Can i work on this

**Comment by DestinedCodes** [comment]
Sure you can. Its been assigned yo you

**Comment by DestinedCodes** [comment]
![Screenshot_from_2023-04-03_13-58-47](https://user-images.githubusercontent.com/84413505/229595843-aae5b2e1-4ebf-4d2f-b66a-d419db251a82.png)
![Screenshot_from_2023-04-03_13-59-27](https://user-images.githubusercontent.com/84413505/229595853-710ad033-e178-4745-ab64-199f8f576126.png)
Here the designes we wish to achieve.

**Comment by DestinedCodes** [comment]
@emaoumaima is meant to work on this issue, so you both can work together

**Comment by DestinedCodes** [comment]
You can find all icons amd designs in the assests directory

**Comment by DestinedCodes** [comment]
@sebzz2k2 @emaoumaima How's your progress so far?

You can find all designs and icons is the assets directory 
Here is what is expected
![Lumininous Hero Popup](https://user-images.githubusercontent.com/84413505/229768207-b2d8f11e-2762-4994-a415-f6fcedf3342c.png) ![Dark Knight Popup](https://user-images.githubusercontent.com/84413505/229768314-0d4450d9-ae12-4e82-9f87-ab19c9edafb4.png)

There is also a link to designs [here](https://www.figma.com/file/HAvoohIW5WgMC4nPPUISbN/ALX-Dark-Mode-Extension?node-id=3-116&t=1U5VdGVgC6D1JTWn-0) use them as guides
